name: Build and Push Docker image
on: 
  workflow_dispatch:
  push: 
jobs: 
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: JenkinsCiCd
      - name: Docker build
        run: ls
      